disabled_rules: # rule identifiers to exclude from running
  - line_length
  - multiple_closures_with_trailing_closure
  - type_name # conflict with SwiftUI StyleGuide of _Previews

identifier_name:
  min_length:
    warning: 2
    error: 1

excluded:
  - Pods
